//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpcUaForTrubodetal
{
    using System;
    using System.Collections.Generic;

    public partial class ProductionTask
    {
        public int ID { get; set; }
        public string TaskNumber { get; set; }
        public Nullable<int> TaskPosition { get; set; }
        public string Product { get; set; }
        public string ProductBatchNumber { get; set; }
        public string StartSerialNumber { get; set; }
        public Nullable<int> ProductsAmount { get; set; }
        public string PipeBatchNumber { get; set; }
        public string PipeNumber { get; set; }
        public string Heat { get; set; }
        public string SteelType { get; set; }
        public Nullable<int> Diameter { get; set; }
        public Nullable<int> Thickness { get; set; }
        public Nullable<int> PieceLength { get; set; }
        public Nullable<int> PieceQuantity { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> FinishDate { get; set; }
        public string Source { get; set; }
        public Nullable<int> PiceAmount { get; set; }
        public string Operator { get; set; }
        public string Status { get; set; }
        public Nullable<int> PieceLength1 { get; set; }
        public Nullable<int> PieceQuantity1 { get; set; }
        public string Labeling1Piece1 { get; set; }
        public string Labeling2Piece1 { get; set; }
        public Nullable<int> PieceLength2 { get; set; }
        public Nullable<int> PieceQuantity2 { get; set; }
        public string Labeling1Piece2 { get; set; }
        public string Labeling2Piece2 { get; set; }
        public Nullable<int> PieceLength3 { get; set; }
        public Nullable<int> PieceQuantity3 { get; set; }
        public string Labeling1Piece3 { get; set; }
        public string Labeling2Piece3 { get; set; }
        public Nullable<int> PieceLength4 { get; set; }
        public Nullable<int> PieceQuantity4 { get; set; }
        public string Labeling1Piece4 { get; set; }
        public string Labeling2Piece4 { get; set; }
        public Nullable<int> PieceLength5 { get; set; }
        public Nullable<int> PieceQuantity5 { get; set; }
        public string Labeling1Piece5 { get; set; }
        public string Labeling2Piece5 { get; set; }
        public Nullable<int> PieceLength6 { get; set; }
        public Nullable<int> PieceQuantity6 { get; set; }
        public string Labeling1Piece6 { get; set; }
        public string Labeling2Piece6 { get; set; }
        public Nullable<int> PieceLength7 { get; set; }
        public Nullable<int> PieceQuantity7 { get; set; }
        public string Labeling1Piece7 { get; set; }
        public string Labeling2Piece7 { get; set; }
        public Nullable<int> PieceLength8 { get; set; }
        public Nullable<int> PieceQuantity8 { get; set; }
        public string Labeling1Piece8 { get; set; }
        public string Labeling2Piece8 { get; set; }
        public Nullable<int> PieceLength9 { get; set; }
        public Nullable<int> PieceQuantity9 { get; set; }
        public string Labeling1Piece9 { get; set; }
        public string Labeling2Piece9 { get; set; }
        public Nullable<int> PieceLength10 { get; set; }
        public Nullable<int> PieceQuantity10 { get; set; }
        public string Labeling1Piece10 { get; set; }
        public string Labeling2Piece10 { get; set; }
        public Nullable<int> PieceLength11 { get; set; }
        public Nullable<int> PieceQuantity11 { get; set; }
        public string Labeling1Piece11 { get; set; }
        public string Labeling2Piece11 { get; set; }
        public Nullable<int> PieceLength12 { get; set; }
        public Nullable<int> PieceQuantity12 { get; set; }
        public string Labeling1Piece12 { get; set; }
        public string Labeling2Piece12 { get; set; }
        public Nullable<int> PieceLength13 { get; set; }
        public Nullable<int> PieceQuantity13 { get; set; }
        public string Labeling1Piece13 { get; set; }
        public string Labeling2Piece13 { get; set; }
        public Nullable<int> PieceLength14 { get; set; }
        public Nullable<int> PieceQuantity14 { get; set; }
        public string Labeling1Piece14 { get; set; }
        public string Labeling2Piece14 { get; set; }
        public Nullable<int> PieceLength15 { get; set; }
        public Nullable<int> PieceQuantity15 { get; set; }
        public string Labeling1Piece15 { get; set; }
        public string Labeling2Piece15 { get; set; }
        public string BandBrand { get; set; }
        public string BandType { get; set; }
        public Nullable<double> BandSpeed { get; set; }
        public Nullable<double> SawDownSpeed { get; set; }
        public Nullable<int> IDOperatorNumber { get; set; }
    }
}
